name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt5/Qt6 (yaqti)
      # You may pin to the exact commit or the version.
      # uses: WillBrennan/yaqti@8182822afd102e931137d71da54f52a13597af8d
      uses: WillBrennan/yaqti@2021.07.29
      with:
        version: 
           5.15.2  # Qt version to pick 5.15.2 or 6.2.1
        os: 
          linux # install os; linux, windows, or mac
        platform: 
          desktop # what platform are you installing for? desktop, winrt, android, or ios
        modules: 
          gcc_64 # what optional Qt modules to install? qtcharts, qtnetworkauth ect...

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        ls -la $Qt5_DIR
        echo "------------------------"       
        ls -la $Qt5_DIR/gcc_64
        echo "------------------------"
        ls -la $Qt5_DIR/gcc_64/lib/cmake
        echo "------------------------"
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=$Qt5_DIR/gcc_64/lib/cmake/Qt5

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
